[package]
name = "rust-test"
version = "0.1.0"
authors = ["장승호(Seung Ho Jang) <shjang1992@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slack = ""
regex = ""
url = ""