version: "3.7"

services:
  ditto_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: registry.skyser.kr/shipduck/ditto_bot_rust
    environment:
      - SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN=$SLACK_APP_TOKEN
      - SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET
      - REDIS_ADDRESS=$REDIS_ADDRESS
      - RUST_LOG=$RUST_LOG
      - BOT_ID=$BOT_ID
      - OPENAI_KEY=$OPENAI_KEY
      - GEMINI_KEY=$GEMINI_KEY
      - USE_GPT_STREAM=$USE_GPT_STREAM
      - OPENAI_MODEL=$OPENAI_MODEL
      - SOCKET_MODE=$SOCKET_MODE
    ports:
      - 2525:8082
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data:
