version: "3.7"

services:
  ditto_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: registry.skyser.kr/shipduck/ditto_bot_rust
    environment:
      - SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
      - SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET
    ports:
      - 2525:8082
