kind: pipeline
type: docker
name: ditto_bot_rust

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    registry: registry.skyser.kr
    repo: registry.skyser.kr/shipduck/ditto_bot_rust
    dockerfile: /drone/src/docker/Dockerfile

- name: publish
  image: alpine
  command:
  - sh
  - -c
  - apk add --update curl && curl -X POST $portainer_webhook
  environment:
   portainer_webhook:
     from_secret: portainer_webhook
  when:
    branch:
    - master
    event:
    - push

---
  kind: pipeline
  type: docker
  name: ditto_bot_rust_ci

  platform:
    os: linux
    arch: arm64

  steps:
  - name: ci
    image: rust
    commands:
      - rustup update
      - rustup component add clippy rustfmt
      - cargo clippy
      - cargo fmt -- --check
