name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check format
      run: cargo fmt -- --check

    - name: Check editorconfig
      run: |
        VERSION="2.1.0"
        OS="linux"
        case $(uname -m) in
        armhf)
          ARCH="arm"
          ;;
        x86_64)
          ARCH="amd64"
          ;;
        i386)
          ARCH="386"
          ;;
        esac
        curl -O -L -C - https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$VERSION/ec-$OS-$ARCH.tar.gz
        tar xzf ec-$OS-$ARCH.tar.gz
        ./bin/ec-$OS-$ARCH

    - name: Run tests
      run: cargo test --verbose

    - name: Check clippy
      run: cargo clippy

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Push
      run: docker/build.sh

    - name: Publish
      run: curl -X POST ${{secrets.PORTAINER_WEBHOOK}}
