name: Rust

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check format
        run: cargo fmt -- --check

      - name: Check editorconfig
        run: |
          VERSION="2.1.0"
          OS="linux"
          case $(uname -m) in
          armhf)
            ARCH="arm"
            ;;
          x86_64)
            ARCH="amd64"
            ;;
          i386)
            ARCH="386"
            ;;
          esac
          curl -O -L -C - https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$VERSION/ec-$OS-$ARCH.tar.gz
          tar xzf ec-$OS-$ARCH.tar.gz
          ./bin/ec-$OS-$ARCH

      - name: Run tests
        run: cargo test --verbose --all-features

      - name: Check clippy
        run: cargo clippy --all-features

  deploy:
    runs-on: ubuntu-latest
    #needs: test_and_check
    if: github.ref == 'refs/heads/release'

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build
        run: bash docker/build.sh

      - name: Push
        run: bash docker/push.sh

      - name: Publish
        if: ${{ github.event_name == 'push' }}
        run: curl -X POST ${{secrets.PORTAINER_WEBHOOK}}
